### ISSUE TITLE
HTTP_PROXY

### ISSUE THREAD

**Issue by htmldrum** [fatzebra/Ruby-Library#10]
Hello,

You've been visited by the fairy of http_proxy support.
I travel the internet, patching libraries to get them to support http_proxy.

I'm having issues with this library and have manually patched it to support http_proxy. More than happy to share.

**Comment by htmldrum** [comment]
J/K you good.

**Comment by StanBright** [comment]
☮

**Comment by htmldrum** [comment]
J/K not really.

Since Ruby 2.0, if the 3rd arg is not provided to Net::HTTP.new, it takes its proxy configuration from the environment. http://ruby-doc.org/stdlib-2.0.0/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new In its current form, this lib is a leaky abstraction over this. Got a P/R to pull the lib into line with Ruby 2.0
