### ISSUE TITLE
Is there more documentation about doing ACH/Direct Debit transactions with this gem?

### ISSUE THREAD

**Issue by michaellee** [fatzebra/Ruby-Library#21]
I've got a client who would like to integrate with Fat Zebra to run transactions but specifically direct debit. I tried going to the link for the docs, http://docs.fatzebra.com.au/ but it seems to go to a different site for CloudPayments, but didn't see anything about using this gem with direct debit.

**Comment by keithbro** [comment]
Hi Michael, thanks for your query. Would you be able to email support@cloudpayments.com.au and our support team will be happy to assist you with this.
